# set default values
# $env:VAGRANT_FORCE_COLOR      = 'true'
path_to_roles_inside_vm = '/data/roles'
path_to_galaxy_requirements = '/vagrant/ansible_development/vagrant/requirements.yml'
path_to_provision_playbook = '/vagrant/ansible_development/vagrant/provision_me.yml'
ansible_roles_path = '/data/roles:/vagrant/'

Vagrant.configure('2') do |config|

  config.ssh.insert_key = false

  config.vm.synced_folder '../../',
                          '/vagrant',
                          mount_options: ['dmode=775,fmode=644']
  config.vm.box = 'bento/centos-7.8'

  config.vm.provision "Set permissions to #{path_to_roles_inside_vm}",
                      type: :shell,
                      inline: "mkdir -p #{path_to_roles_inside_vm} ;
                               chmod o+w #{path_to_roles_inside_vm}
                              "

  config.vm.provision 'ansible_local' do |ansible|
    ansible.install_mode = "pip3"
    ansible.version = "2.9.18"
    ansible.playbook = path_to_provision_playbook
    ansible.galaxy_roles_path = ansible_roles_path
    ansible.galaxy_role_file = path_to_galaxy_requirements
    ansible.verbose = 'vvv'
  end

end
